import type { Config } from "tailwindcss";

const tokenColor = (token: string) =>
  `color-mix(in srgb, var(--${token}) calc(<alpha-value> * 100%), transparent)`;

const config: Config = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Geist Variable"', "Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        display: ['"DM Serif Display"', "Georgia", "serif"],
        dm: ['"DM Sans"', "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        card: "var(--shadow-card)",
      },
      colors: {
        background: tokenColor("background"),
        foreground: tokenColor("foreground"),
        surface: {
          DEFAULT: tokenColor("surface"),
          muted: tokenColor("surface-muted"),
          hover: tokenColor("surface-hover"),
        },
        card: tokenColor("card"),
        "card-foreground": tokenColor("card-foreground"),
        popover: tokenColor("popover"),
        "popover-foreground": tokenColor("popover-foreground"),
        primary: {
          DEFAULT: tokenColor("primary"),
          foreground: tokenColor("primary-foreground"),
          muted: tokenColor("primary-muted"),
          50: "var(--brand-50)",
          100: "var(--brand-100)",
          200: "var(--brand-200)",
          300: "var(--brand-300)",
          400: "var(--brand-400)",
          500: "var(--brand-500)",
          600: "var(--brand-600)",
          700: "var(--brand-700)",
          800: "var(--brand-800)",
          900: "var(--brand-900)",
          950: "var(--brand-950)",
        },
        "primary-foreground": tokenColor("primary-foreground"),
        secondary: tokenColor("secondary"),
        "secondary-foreground": tokenColor("secondary-foreground"),
        muted: tokenColor("muted"),
        "muted-foreground": tokenColor("muted-foreground"),
        accent: tokenColor("accent"),
        "accent-foreground": tokenColor("accent-foreground"),
        destructive: tokenColor("destructive"),
        "destructive-foreground": tokenColor("destructive-foreground"),
        border: tokenColor("border"),
        "border-subtle": tokenColor("border-subtle"),
        input: tokenColor("input"),
        ring: tokenColor("ring"),
        success: {
          DEFAULT: tokenColor("success"),
          foreground: tokenColor("success-foreground"),
          50: "var(--success-50)",
          100: "var(--success-100)",
          400: "var(--success-400)",
          600: "var(--success-600)",
          800: "var(--success-800)",
        },
        warning: {
          DEFAULT: tokenColor("warning"),
          foreground: tokenColor("warning-foreground"),
          50: "var(--warning-50)",
          100: "var(--warning-100)",
          400: "var(--warning-400)",
          600: "var(--warning-600)",
          800: "var(--warning-800)",
        },
        danger: {
          DEFAULT: tokenColor("destructive"),
          50: "var(--danger-50)",
          100: "var(--danger-100)",
          400: "var(--danger-400)",
          600: "var(--danger-600)",
          800: "var(--danger-800)",
        },
        info: {
          DEFAULT: tokenColor("info"),
          foreground: tokenColor("info-foreground"),
        },
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          400: "var(--neutral-400)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
        },
      },
    },
  },
  plugins: [],
};

export default config;
